"""Auto migration for schedule update

Revision ID: 364d0116ade0
Revises: 
Create Date: 2026-02-12 16:19:03.627341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364d0116ade0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('degree_level', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplines', schema=None) as batch_op:
        batch_op.drop_column('degree_level')
        batch_op.drop_column('department')

    # ### end Alembic commands ###
