"""Add global_settings table

Revision ID: da15973077dd
Revises: 3d233fcfad51
Create Date: 2026-02-13 10:28:47.147895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da15973077dd'
down_revision = '3d233fcfad51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_user', sa.String(length=100), nullable=True),
    sa.Column('email_password', sa.String(length=100), nullable=True),
    sa.Column('email_to', sa.String(length=500), nullable=True),
    sa.Column('smtp_server', sa.String(length=100), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('interval_weekday', sa.Integer(), nullable=True),
    sa.Column('interval_weekend', sa.Integer(), nullable=True),
    sa.Column('alert_threshold', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_settings')
    # ### end Alembic commands ###
